### PR TITLE
Make additional_data available too.

### PR DESCRIPTION
**Pull request by grindars**
This is necessary to get dropbox_email from deal.

### CODE REVIEW

**Comment by grindars** [comment]
What about this PR? Will it be merged?

**Comment by ai** [comment]
Any updated? I need this fix too.

**Comment by ai** [comment]
Can you release new version with this fix?

**Comment by ai** [comment]
@jeanmartin release? :)

**Comment by ai** [comment]
@jeanmartin could you please release new gem version with this fix?

**Comment by ai** [comment]
@jeanmartin maybe I can help somehow?

**Comment by ai** [comment]
@GeneralScripting @brunogh @jeanmartin could you please release new gem version with this fix? ;)

**Comment by brunogh** [comment]
@ai, I would love to, but I cannot release.

You can try to point out to the Github master branch while wait for it (http://stackoverflow.com/questions/17007277/point-gem-branch-path-in-gemfile).

**Comment by jeanmartin** [comment]
Finally released it (0.3.3). Sorry guys for keeping you waiting. I'll try to be better at maintaining this :)

**Comment by ai** [comment]
Thanks! This gem was only gem from master in our `Gemfile` :).

**Pull request merged**
