### PR TITLE
Enhanced and added feature sets (incomplete though)

### PR DESCRIPTION
**Pull request by jufemaiz**
Added a bunch of functionality - will continue to update as I test each of the features added to the API.

### CODE REVIEW

**Comment by Meekohi** [comment]
I'd recommend pulling this in. I am using Joel's fork in production with no issues and it has better coverage of the Pipedrive API.

**Comment by kitop** [comment]
Any ETA for this to be merged?

**Comment by ajb** [comment]
:thumbsup: please merge!

**Comment by matgren** [comment]
:+1: merge

**Pull request merged**
